/*
 * VideoCore IV (VC4) Shader Assembler Interface
 */

#ifndef VC4_SHADER_ASSEMBLER_H
#define VC4_SHADER_ASSEMBLER_H

#include "v3d_types.h"
#include "v3d_device.h"

#define V3D_SHADER_MAX_INSTRUCTIONS 128

typedef struct V3DAssembledShader {
    v3d_qpu_instruction instructions[V3D_SHADER_MAX_INSTRUCTIONS];
    int numInstructions;
} V3DAssembledShader;

enum {
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED = 0,
    V3D_SHADER_VARIANT_VERTEX_TEXTURED,
    V3D_SHADER_VARIANT_COORDINATE_TEXTURED,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_ALPHATEST,

    V3D_SHADER_VARIANT_VERTEX_SMOOTH,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_SMOOTH,

    V3D_SHADER_VARIANT_VERTEX_SMOOTH_TEXTURED,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH,

    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_ALPHATEST,

    V3D_SHADER_VARIANT_VERTEX_MULTITEXTURE,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_BLEND,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_BLEND_ADD,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_SMOOTH_BLEND_ADD,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_SMOOTH_BLEND,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_BLEND,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_BLEND,

    V3D_SHADER_VARIANT_COORDINATE_CLIPSPACE,
    V3D_SHADER_VARIANT_VERTEX_SMOOTH_TEXTURED_CLIPSPACE,
    V3D_SHADER_VARIANT_VERTEX_MULTITEXTURE_CLIPSPACE,

    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_DECAL,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_REPLACE,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_MODULATE_BLEND,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_DECAL_BLEND,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_REPLACE_BLEND,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_ALPHATEST_GREATER,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_ALPHATEST_GREATER,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_PADDED_FLAT_TEST,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_MODULATE_TRANSLUCENT,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_COLORMOD,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_BLEND_ADD,

    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_DSTCOLOR_ZERO,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_DSTCOLOR_ONE,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_DSTCOLOR_SRCCOLOR,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_DSTCOLOR_INVDSTALPHA,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ZERO_INVSRCCOLOR,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_DSTCOLOR_SRCALPHA,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ONE_INVSRCALPHA,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_INVSRCALPHA_SRCALPHA,

    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ALPHATEST_GREATER,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ALPHATEST,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_BLEND_SRCALPHA_ONE,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_SMOOTH_BLEND_SRCALPHA_ONE,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_BLEND_SRCALPHA_ONE,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_ALPHATEST_NEVER,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_ALPHATEST_NEVER,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ALPHATEST_NEVER,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_ALPHATEST_LESS,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_ALPHATEST_LESS,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ALPHATEST_LESS,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_ALPHATEST_EQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_ALPHATEST_EQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ALPHATEST_EQUAL,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_ALPHATEST_LEQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_ALPHATEST_LEQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ALPHATEST_LEQUAL,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_ALPHATEST_NOTEQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_ALPHATEST_NOTEQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ALPHATEST_NOTEQUAL,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_FOG_ALPHATEST,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_FOG_ALPHATEST,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_FOG_ALPHATEST_GREATER,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_FOG_ALPHATEST_GREATER,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_FOG_ALPHATEST_LESS,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_FOG_ALPHATEST_LESS,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_FOG_ALPHATEST_EQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_FOG_ALPHATEST_EQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_FOG_ALPHATEST_LEQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_FOG_ALPHATEST_LEQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_FOG_ALPHATEST_NOTEQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_FOG_ALPHATEST_NOTEQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_FOG_ALPHATEST_NEVER,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_FOG_ALPHATEST_NEVER,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_SMOOTH_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_FOG_ALPHATEST,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_FOG_ALPHATEST_GREATER,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_FOG_ALPHATEST_LESS,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_FOG_ALPHATEST_EQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_FOG_ALPHATEST_LEQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_FOG_ALPHATEST_NOTEQUAL,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_FOG_ALPHATEST_NEVER,

    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_DECAL_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_REPLACE_FOG,

    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_BLEND_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_BLEND_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_DSTCOLOR_ZERO_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_DSTCOLOR_ONE_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_DSTCOLOR_SRCCOLOR_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_DSTCOLOR_INVDSTALPHA_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ZERO_INVSRCCOLOR_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_DSTCOLOR_SRCALPHA_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_ONE_INVSRCALPHA_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_INVSRCALPHA_SRCALPHA_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_MODULATE_TRANSLUCENT_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_MODULATE_BLEND_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_DECAL_BLEND_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_MULTITEXTURE_REPLACE_BLEND_FOG,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_SMOOTH_BLEND_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_SMOOTH_BLEND_ADD_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_SMOOTH_BLEND_SRCALPHA_ONE_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_BLEND_ADD_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_BLEND_SRCALPHA_ONE_FOG,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_BLEND_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_BLEND_ADD_FOG,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_BLEND_SRCALPHA_ONE_FOG,

    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_POINT_SMOOTH,
    V3D_SHADER_VARIANT_FRAGMENT_UNTEXTURED_SMOOTH_POINT_SMOOTH,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_POINT_SMOOTH,
    V3D_SHADER_VARIANT_FRAGMENT_TEXTURED_SMOOTH_POINT_SMOOTH,

    V3D_MAX_SHADER_VARIANTS = 114
};

extern V3DAssembledShader v3d_shader_variants[V3D_MAX_SHADER_VARIANTS];
int v3d_assemble_builtin_shaders(V3DDevice* device);

#endif /* VC4_SHADER_ASSEMBLER_H */
